### ISSUE TITLE
Setup with latest ONS data

### ISSUE THREAD

**Issue by Goran-n** [ONSdigital/address-index-data#201]
The latest ONS Addressbase Premium data is presented in zip files which contain grouped data categorised by the postcode. 
This results in over 10000 files that need to get processed.

It would appear that the current solution only accepts 1 CSV file for each type of record type.

**Comment by steve-thorne-ONS** [comment]
The AddresssBase Premium data undergoes a number of internal pre-processing tasks to get the data into a usable format. You would need to adapt the data to match the test data or adapt the code to work with the original source.
